-- 1. Create the Module table
CREATE TABLE MODULE (
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    MODULE_NAME VARCHAR(50),
    DESCRIPTION VARCHAR(255),
    PRIMARY KEY (ID)
);

-- 2. Create the Rights table
CREATE TABLE RIGHTS (
    ID INT NOT NULL PRIMARY KEY,
    RIGHT_NAME VARCHAR(50),
    DESCRIPTION VARCHAR(100)
);

-- 3. Create the UserModule_Rights junction table
CREATE TABLE USERMODULE_RIGHTS (
    USER_ID INT NOT NULL,
    MODULE_ID INT NOT NULL,
    RIGHT_ID INT NOT NULL,
    PRIMARY KEY (USER_ID, MODULE_ID)
);
